export const POLICY_STATUSES = {
  PENDING_PAYMENT: 'PENDING_PAYMENT',
  ACTIVE: 'ACTIVE',
  EXPIRED: 'EXPIRED',
  CANCELLED: 'CANCELLED',
}

export const CLAIM_STATUSES = {
  SUBMITTED: 'SUBMITTED',
  UNDER_REVIEW: 'UNDER_REVIEW',
  RECOMMENDED_APPROVAL: 'RECOMMENDED_APPROVAL',
  RECOMMENDED_REJECTION: 'RECOMMENDED_REJECTION',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
}

export const PAYMENT_MODES = {
  UPI: 'UPI',
  CARD: 'CARD',
  NET_BANKING: 'NET_BANKING',
  CASH: 'CASH',
}

export const PRODUCT_TYPES = {
  HEALTH: 'HEALTH',
  MOTOR: 'MOTOR',
  LIFE: 'LIFE',
  TRAVEL: 'TRAVEL',
}

export const PREMIUM_TYPES = {
  ONE_TIME: 'ONE_TIME',
  ANNUAL: 'ANNUAL',
}

export const DEFAULT_PAGE_SIZE = 10

export const MAX_PAGE_SIZE = 100

export const DEFAULT_SORT = 'createdAt'

export const DEFAULT_SORT_DIR = 'ASC'
